class NotFoundError(Exception):
    pass

class FailedLoginError(Exception):
    pass
